version: '3'
services:
    backend:
      image: backend:1.0
      ports:
        - 3000:3000
    mongodb:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./data/db:/data/db
    mongo-express:
      image: mongo-express
      ports:
          - 8080:8081

